name : CI

on:  
  pull_request:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: codebase

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SETUP NODE.js
        uses: actions/setup-node@v4
        with:

          node-version: '15'
          cache: npm
          cache-dependency-path: codebase/package-lock.json

      - name: Install
        run: npm Install
      
      - name: LINT 
        run: npm run lint
      
      - name: TEST
        run: CI=true npm run test

      - name: build
        run: npm run build
    